
# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . .

# Set environment variables
# ENV FLASK_APP=app.py
# ENV FLASK_RUN_HOST=0.0.0.0
# ENV TARGET_URL=https://api.ppe.supplychain.microsoft.com/migration-test

# Expose the port the app runs on
EXPOSE 8080
EXPOSE 8443

# Command to run when the container starts
CMD ["python", "app.py"]